<a href="https://colab.research.google.com/github/yashasangani/Machine-Learning/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [8]:
def step_gradient(points,learning_rate,m,c):
  m_slope = 0
  c_slope = 0
  M = len(points)
  for i in range(M):
    x = points[i,0]
    y = points[i,1]
    m_slope = m_slope +((-2/M)*(y-m * x -c) * x)
    c_slope = c_slope + ((-2/M) * (y-m * x -c))
  new_m = m - learning_rate*m_slope
  new_c = c - learning_rate*c_slope
  return new_m,new_c

In [9]:
def gd(points,learning_rate,num_iterations):
  m=0
  c=0
  for i in range(num_iterations):
    m,c= step_gradient(points,learning_rate,m,c)
    print(i,"cost: ", cost(points,m,c))
  return m,c


In [10]:
def cost(points,m,c):
  total_cost = 0
  M = len(points)
  for i in range(M):
    x = points[i,0]
    y = points[i,1]
    total_cost +=(1/M) * ((y-m*x - c) **2)
  return total_cost

In [20]:
def run():
  data = np.loadtxt('/content/data 2.csv',delimiter =',')
  learning_rate = 0.001
  num_iterations = 100
  m,c = gd(data,learning_rate,num_iterations)
  print(m,c)

In [21]:
run()

FileNotFoundError: /content/data 2.csv not found.

# another way

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])


In [22]:
def gradient_descent(x,y):
  m = 0
  c = 0
  n = len(x)
  learning_rate = 0.08
  iterations = 1000
  for i in range(iterations):
    y_pred = m * x + c
    cost = (1/n) * sum([val**2 for val in (y-y_pred)])
    md = (-2/n) * sum (x * (y-y_pred))
    cd = (-2/n) * sum (y-y_pred)
    m = m - learning_rate * md
    c = c - learning_rate * cd
    print(f"iterations = {i},cost = {cost}")
  print(f"m = {m},c = {c}")


In [23]:
gradient_descent(x,y)

iterations = 0,cost = 89.0
iterations = 1,cost = 71.10560000000002
iterations = 2,cost = 56.8297702400001
iterations = 3,cost = 45.43965675929613
iterations = 4,cost = 36.35088701894832
iterations = 5,cost = 29.097483330142282
iterations = 6,cost = 23.307872849944438
iterations = 7,cost = 18.685758762535738
iterations = 8,cost = 14.994867596913156
iterations = 9,cost = 12.046787238456794
iterations = 10,cost = 9.691269350698109
iterations = 11,cost = 7.8084968312098315
iterations = 12,cost = 6.302918117062937
iterations = 13,cost = 5.098330841763168
iterations = 14,cost = 4.133961682056365
iterations = 15,cost = 3.361340532576948
iterations = 16,cost = 2.741808050753047
iterations = 17,cost = 2.244528230107478
iterations = 18,cost = 1.8449036666988363
iterations = 19,cost = 1.5233119201782324
iterations = 20,cost = 1.2640979056612756
iterations = 21,cost = 1.0547704368105268
iterations = 22,cost = 0.8853615531285766
iterations = 23,cost = 0.7479156468369821
iterations = 24,cost = 0.636

# One more example

In [25]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/3_gradient_descent/Exercise/test_scores.csv')

In [30]:
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [78]:
x = df.iloc[:,1]
x = np.array(x)
x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67])

In [79]:
y = df.iloc[:,2]
y = np.array(y)
y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73])

In [82]:
def gradient_descent(x,y):
  m = 0
  c = 0
  learning_rate = 0.0002
  iterations = 1000000
  n = len(x)
  for i in range(iterations):
    y_pred = m * x + c
    cost = (1/n) * sum([val**2 for val in (y-y_pred)])
    md = (-2/n) * sum(x * (y-y_pred))
    cd = (-2/n) * sum(y-y_pred)
    m = m - learning_rate * md
    c = c - learning_rate * cd
    print(f"iterations = {i},cost = {cost}")
  print(f"m = {m} , c = {c}")

In [83]:
gradient_descent(x,y)

Streaming output truncated to the last 5000 lines.
iterations = 995001,cost = 31.604511333529572
iterations = 995002,cost = 31.604511333529583
iterations = 995003,cost = 31.604511333529594
iterations = 995004,cost = 31.604511333529583
iterations = 995005,cost = 31.604511333529583
iterations = 995006,cost = 31.604511333529587
iterations = 995007,cost = 31.604511333529622
iterations = 995008,cost = 31.604511333529572
iterations = 995009,cost = 31.604511333529572
iterations = 995010,cost = 31.604511333529583
iterations = 995011,cost = 31.604511333529604
iterations = 995012,cost = 31.604511333529572
iterations = 995013,cost = 31.6045113335296
iterations = 995014,cost = 31.6045113335296
iterations = 995015,cost = 31.6045113335296
iterations = 995016,cost = 31.604511333529583
iterations = 995017,cost = 31.604511333529587
iterations = 995018,cost = 31.604511333529583
iterations = 995019,cost = 31.60451133352961
iterations = 995020,cost = 31.604511333529583
iterations = 995021,cost = 31.604511

In [73]:
x = np.reshape(x, (-1, 1))

In [76]:
x.reshape(1,-1)

from sklearn.linear_model import LinearRegression
alg = LinearRegression()
alg.fit(x,y)
ypred = alg.predict(x)

In [84]:
alg.coef_, alg.intercept_,alg.score

(array([1.01773624]),
 1.9152193111569034,
 <bound method RegressorMixin.score of LinearRegression()>)