<a href="https://colab.research.google.com/github/yashasangani/Machine-Learning/blob/main/Pipeline/Predict_without_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from warnings import filterwarnings
filterwarnings('ignore')

In [24]:
import pickle
import numpy as np

In [25]:
oe_sex = pickle.load(open('/oe_sex.pkl','rb'))
oe_embarked = pickle.load(open('/oe_embarked.pkl','rb'))
clf = pickle.load(open('/clf.pkl','rb'))

In [26]:
# Assume user input
# Pclass/gender/age/Sibsp/Parch/Fare/Embarked

test_input = np.array([2,'male' , 31.0 , 0,0,10.5,'S'],dtype = object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [27]:
test_input_sex = oe_sex.transform(test_input[:,1].reshape(1,1))

In [28]:
test_input_embarked = oe_embarked.transform(test_input[:,-1].reshape(1,1))

In [29]:
test_input_embarked

array([[0., 0., 1.]])

In [30]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[31.0]], dtype=object)

In [34]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis = 1)

In [35]:
test_input_transformed.shape

(1, 10)

In [36]:
clf.predict(test_input_transformed)

array([0])